---
http_interactions:
- request:
    method: post
    uri: http://kanbanize.com/index.php/api/kanbanize/get_board_settings/boardid/2/format/json
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Apikey:
      - testapikey
  response:
    status:
      code: 200
      message: OK
    headers:
      Via:
      - 1.1 TMG
      Connection:
      - Keep-Alive
      Proxy-Connection:
      - Keep-Alive
      Transfer-Encoding:
      - chunked
      Date:
      - Mon, 24 Jun 2013 13:59:08 GMT
      Content-Type:
      - application/json
      Server:
      - Apache
      Set-Cookie:
      - ci_csrf_token=a0417a1fddfe51d40ca143c95797f901; expires=Mon, 24-Jun-2013 21:59:08
        GMT; path=/
      - ci_session=a%3A4%3A%7Bs%3A10%3A%22session_id%22%3Bs%3A32%3A%226d6b890a1bd108ce427d9a3e132910d8%22%3Bs%3A10%3A%22ip_address%22%3Bs%3A13%3A%2292.103.209.40%22%3Bs%3A10%3A%22user_agent%22%3Bs%3A46%3A%22Mozilla%2F4.0+%28compatible%3B+MSIE+5.5%3B+Windows+98%29%22%3Bs%3A13%3A%22last_activity%22%3Bi%3A1372082348%3B%7Da3243038ea2efdd6fc068ddb3034cf63;
        path=/
    body:
      encoding: US-ASCII
      string: ! '{"usernames":["karouf"],"templates":["Bug","Feature","Support"],"types":["Bug","Feature
        request","Support request"]}'
    http_version: 
  recorded_at: Mon, 24 Jun 2013 13:59:41 GMT
recorded_with: VCR 2.5.0
